variable "env_id" {}
variable "region" {}
variable "account_id" {}
variable "vpc_id" {}
variable "private_subnets" {}
variable "security_group" {}
variable "cluster_arn" {}
variable "jdbcUrl" {}
variable "jdbcUsername" {}
variable "jdbcPassword" {}
